### ISSUE TITLE
build_index can't handle empty numpy files

### ISSUE THREAD

**Issue by sgutwein** [criteo/autofaiss#117]
Hello,

I'm currently running a workflow in argo which is generating several embedding files, in parallel, based on a database search.
If no data was found, the workflow returns a empty numpy file:

`np.save(os.path.join(output, "features", filename), np.empty(0, np.float32))`

Sadly the `build_index` is not capable of handling those files:

```
Using 4 omp threads (processes), consider increasing --nb_cores if you have more
Launching the whole pipeline 04/08/2022, 09:35:41
Reading total number of vectors and dimension 04/08/2022, 09:35:41

  0%|          | 0/16 [00:00<?, ?it/s]
 50%|█████     | 8/16 [00:00<00:00, 109.51it/s]
>>> Finished "Reading total number of vectors and dimension" in 0.1098 secs
>>> Finished "Launching the whole pipeline" in 0.1098 secs
Traceback (most recent call last):
  File "/usr/local/bin/autofaiss", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/autofaiss/external/quantize.py", line 395, in main
    fire.Fire({"build_index": build_index, "tune_index": tune_index, "score_index": score_index})
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/autofaiss/external/quantize.py", line 143, in build_index
    nb_vectors, vec_dim = read_total_nb_vectors_and_dim(
  File "/usr/local/lib/python3.8/site-packages/autofaiss/readers/embeddings_iterators.py", line 258, in read_total_nb_vectors_and_dim
```
Would be great if it could handle it, by just showing a waning in the logs or a flag to allow it.

**Comment by rom1504** [comment]
Given that stack trace, you're using an outdated version of autofaiss, can you try to update it?

**Comment by sgutwein** [comment]
The stack trace, after updating the image:

```
2022-04-08 10:28:50,405 [INFO]: Using 4 omp threads (processes), consider increasing --nb_cores if you have more
2022-04-08 10:28:50,406 [INFO]: Launching the whole pipeline 04/08/2022, 10:28:50
2022-04-08 10:28:50,406 [INFO]: Reading total number of vectors and dimension 04/08/2022, 10:28:50

  0%|          | 0/16 [00:00<?, ?it/s]
 56%|█████▋    | 9/16 [00:00<00:00, 1511.52it/s]
2022-04-08 10:28:50,500 [INFO]: >>> Finished "Reading total number of vectors and dimension" in 0.0947 secs
2022-04-08 10:28:50,502 [INFO]: >>> Finished "Launching the whole pipeline" in 0.0964 secs
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/embedding_reader/numpy_reader.py", line 46, in file_to_header
    return (None, [filename, *read_numpy_header(f)])
  File "/usr/local/lib/python3.8/site-packages/embedding_reader/numpy_reader.py", line 28, in read_numpy_header
    shape = (int(result.group(1)), int(result.group(2)))
AttributeError: 'NoneType' object has no attribute 'group'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/autofaiss", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/autofaiss/external/quantize.py", line 484, in main
    fire.Fire({"build_index": build_index, "tune_index": tune_index, "score_index": score_index})
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/autofaiss/external/quantize.py", line 209, in build_index
    embedding_reader = EmbeddingReader(
  File "/usr/local/lib/python3.8/site-packages/embedding_reader/embedding_reader.py", line 20, in __init__
    self.reader = NumpyReader(embeddings_folder)
  File "/usr/local/lib/python3.8/site-packages/embedding_reader/numpy_reader.py", line 55, in __init__
    raise Exception(f"failed reading file {c[0]}") from err
Exception: failed reading file /tmp/outputs/features/data_9.npy
```

**Comment by rom1504** [comment]
Ok that's a check to add there
https://github.com/rom1504/embedding-reader/blob/main/embedding_reader/numpy_reader.py#L27
I'll add it

I'm however surprised this doesn't work as we have a test for this exactly

Are you creating empty numpy files or completely empty files ?

**Comment by sgutwein** [comment]
Empty numpy files as described above:

`np.save(os.path.join(output, "features", filename), np.empty(0, np.float32))`
