### ISSUE TITLE
get_optimal_index_keys_v2 returns an empty list

### ISSUE THREAD

**Issue by edoost** [criteo/autofaiss#118]
I am using autofaiss 2.14.0 and it works for some parts of the data I am working on, but not for some. I keep getting this error and I do not know where to look at:

```
2022-04-21 17:46:40,649 [INFO]: There are 16325691 embeddings of dim 768
2022-04-21 17:46:40,653 [INFO]: >>> Finished "Reading total number of vectors and dimension" in 37.7308 secs
2022-04-21 17:46:40,653 [INFO]:         Compute estimated construction time of the index 04/21/2022, 17:46:40
2022-04-21 17:46:40,659 [INFO]:                 -> Train: 16.7 minutes
2022-04-21 17:46:40,659 [INFO]:                 -> Add: 2.3 minutes
2022-04-21 17:46:40,659 [INFO]:                 Total: 19.0 minutes
2022-04-21 17:46:40,659 [INFO]:         >>> Finished "Compute estimated construction time of the index" in 0.0057 secs
2022-04-21 17:46:40,659 [INFO]:         Checking that your have enough memory available to create the index 04/21/2022, 17:46:40
2022-04-21 17:46:40,802 [INFO]:         >>> Finished "Checking that your have enough memory available to create the index" in 0.1431 secs
2022-04-21 17:46:40,803 [INFO]: >>> Finished "Launching the whole pipeline" in 37.8808 secs
Traceback (most recent call last):
  File "process.py", line 26, in <module>
    chunks_to_precalculated_knn_(
  File "/home/x_ehsdo/.local/lib/python3.8/site-packages/retro_pytorch/retrieval.py", line 373, in chunks_to_precalculated_knn_
    index, embeddings = chunks_to_index_and_embed(
  File "/home/x_ehsdo/.local/lib/python3.8/site-packages/retro_pytorch/retrieval.py", line 334, in chunks_to_index_and_embed
    index = index_embeddings(
  File "/home/x_ehsdo/.local/lib/python3.8/site-packages/retro_pytorch/retrieval.py", line 288, in index_embeddings
    build_index(
  File "/home/x_ehsdo/.local/lib/python3.8/site-packages/autofaiss/external/quantize.py", line 224, in build_index
    necessary_mem, index_key_used = estimate_memory_required_for_index_creation(
  File "/home/x_ehsdo/.local/lib/python3.8/site-packages/autofaiss/external/build.py", line 46, in estimate_memory_required_for_index_creation
    index_key = get_optimal_index_keys_v2(
IndexError: list index out of range
```

**Comment by edoost** [comment]
It was apparently a memory problem. Got it solved by increasing the memory parameters.
